# fly.toml app configuration file generated for chorepig on 2023-07-08T22:20:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chorepig"
primary_region = "iad"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
